export const Users = [
        {
        id: 1,
        profilePicture: "assets/person/1.jpeg",
        username: "ShinCode",
        },
        {
        id: 2,
        profilePicture: "assets/person/2.jpeg",
        username: "Yamaki",
        },
        {
        id: 3,
        profilePicture: "assets/person/3.jpeg",
        username: "Koga",
        },
        {
        id: 4,
        profilePicture: "images/iiinuyu.png",
        username: "Matukubo",
        },
        {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Kikukawa",
        },
    ];
    
    export const Posts = [
        {
        id: 1,
        desc: "コツコツの積み重ねが大事。",
        photo: "/images/image1.JPEG",
        date: "5分前",
        userId: 1,
        like: 20,
        comment: 4,
        imageUrl: "/sunny.png",
        profileImage: "",
        },
        {
        id: 2,
        desc: "MERNスタックが楽しすぎる",
        photo: "/images/image1.JPEG",
        date: "2分前",
        userId: 2,
        like: 140,
        comment: 13,
        imageUrl: "/images/image1.JPEG",
        profileImage: "",
        },
        {
        id: 3,
        desc: "ShinCodeさんの解説が分かりやすい。",
        photo: "/sunny.png",
        date: "10分前",
        userId: 3,
        like: 230,
        comment: 29,
        imageUrl: "",
        profileImage: "",
        },
        {
        id: 4,
        desc: "ShinCodeさんの解説が分かりやすい。",
        title: "",
        photo: "/images/image4.jpg",
        date: "1分前",
        userId: 4,
        like: -10,
        comment: 1,
        imageUrl: "/images/image4.jpg",
        profileImage: "",
        },
        {
        id: 5,
        desc: "定期的に散歩した方が生産性が上がる。",
        photo: "/images/image3.jpg",
        date: "1分前",
        userId: 5,
        like: 100,
        comment: 3,
        imageUrl: "",
        profileImage: "",
        },
    ];